#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require "benchmark"
require "css_class_duplicates"

cli = CssClassDuplicates::CLI.new
result = 0

time = Benchmark.realtime { result = cli.run }

puts "Finished in #{time} seconds"
exit result
